package common;

public enum EnumClientOperations{
	UPDATE_WELOCME,
	USER,
	DISPLAY_ORDERS,
	EROR,
	VIEW,
	NONE, PENDING_ORDER, NOTIFICATION, DELETE_DISH, VIEW_MENU, UPDATE_DISH, CREATED_USER, CREATED_ACCOUNT, ADD_DISH, REPORT_ERROR, SQL_ERROR, INCOME_REPORT, ORDERS_REPORT, PERFORMANCE_REPORT, INSERT_ORDER, LOG_OUT, GET_DISCOUNT_AMOUNT, CHECK_USER, SET_DISCOUNT_AMOUNT, UPDATE_ORDER_STATUS, QUARTERLY_REPORT, SHOW_PENDING_ORDERS, DISHES_IN_ORDER, MENU_FOR_UPDATE;
}
