package enums;
//sup
public enum EnumClientOperations{
	USERS_ORDERS,
	USER,
	PENDING_ORDER,
	NOTIFICATION,
	DELETE_DISH,
	VIEW_MENU,
	UPDATE_DISH,
	CREATED_ACCOUNT,
	ADD_DISH,
	REPORT_ERROR,
	INCOME_REPORT,
	ORDERS_REPORT,
	PERFORMANCE_REPORT,
	GET_DISCOUNT_AMOUNT,
	CHECK_USER,
	QUARTERLY_REPORT,
	DISHES_IN_ORDER,
	MENU_FOR_UPDATE,
	CHANGE_HOME_BRANCH,
	INTERRUPT_ORDER_CREATION,
	SERVER_DISCONNECTED,
	ORDER_ON_TIME, 
	INTERRUPT_PENDING_ORDERS;
}