package common;

public enum EnumClientOperations {
	UPDATE_WELOCME,
	USER,
	DISPLAY_ORDERS,
	EROR,
	VIEW,
	NONE, PENDING_ORDER, NOTIFICATION, DELETE_DISH, VIEW_MENU, UPDATE_DISH, CREATED_USER, CREATED_ACCOUNT, ADD_DISH, REPORT_ERROR, SQL_ERROR, INCOME_REPORT, ORDERS_REPORT, PERFORMANCE_REPORT, INSERT_ORDER, LOG_OUT, GET_DISCOUNT_AMOUNT, SET_DISCOUNT_AMOUNT, UPDATE_ORDER_STATUS;
}
