package common;

public enum EnumServerOperations {
	NONE,
	USER_CONDITION,
	INSERT_ORDER,
	UPDATE_ORDER,
	VIEW,
	LOGIN, 
	ADD_DISH,
	NOTIFICATION, PENDING_ORDER, DELETE_DISH, UPDATE_DISH, VIEW_MENU, CREATE_ACCOUNT, INCOME_REPORT, PERFORMANCE_REPORT, ORDERS_REPORT, LOG_OUT, UPDATE_ORDER_STATUS, GET_DISCOUNT_AMOUNT, SET_DISCOUNT_AMOUNT, CHECK_USER
}
